/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as BookCallRouteImport } from './routes/book-call'
import { Route as IndexRouteImport } from './routes/index'

const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCallRoute = BookCallRouteImport.update({
  id: '/book-call',
  path: '/book-call',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-call': typeof BookCallRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pilot': typeof PilotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-call': typeof BookCallRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pilot': typeof PilotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-call': typeof BookCallRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pilot': typeof PilotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book-call' | '/how-it-works' | '/pilot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book-call' | '/how-it-works' | '/pilot'
  id: '__root__' | '/' | '/book-call' | '/how-it-works' | '/pilot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookCallRoute: typeof BookCallRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PilotRoute: typeof PilotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-call': {
      id: '/book-call'
      path: '/book-call'
      fullPath: '/book-call'
      preLoaderRoute: typeof BookCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookCallRoute: BookCallRoute,
  HowItWorksRoute: HowItWorksRoute,
  PilotRoute: PilotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
